# Generated by Django 2.0.4 on 2018-04-16 17:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(choices=[('ABS', 'Abstract'), ('AER', 'Aerial'), ('ANI', 'Animals'), ('ARC', 'Architecture'), ('BLA', 'Black and White'), ('FAM', 'Family'), ('FAS', 'Fashion'), ('FIN', 'Fine Art'), ('FOO', 'Food'), ('JOU', 'Journalism'), ('LAN', 'Landscape'), ('MAC', 'Macro'), ('NAT', 'Nature'), ('NIG', 'Night'), ('PEO', 'People'), ('PER', 'Performing Arts'), ('SPO', 'Sport'), ('STI', 'Still Life'), ('STR', 'Street'), ('TRA', 'Travel')], default='ABS', max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=90)),
                ('description', models.CharField(max_length=280)),
                ('upload_date', models.DateField(default=datetime.date.today)),
                ('num_of_downloads', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Category', to_field='cat_name')),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='tag',
            field=models.ManyToManyField(to='search.Tag'),
        ),
    ]
