# Generated by Django 2.0.2 on 2018-03-23 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='upload')),
                ('title', models.CharField(max_length=90)),
                ('category', models.CharField(choices=[('ABS', 'Abstract'), ('AER', 'Aerial'), ('ANI', 'Animals'), ('ARC', 'Architecture'), ('BLA', 'Black and White'), ('FAM', 'Family'), ('FAS', 'Fashion'), ('FIN', 'Fine Art'), ('FOO', 'Food'), ('JOU', 'Journalism'), ('LAN', 'Landscape'), ('MAC', 'Macro'), ('NAT', 'Nature'), ('NIG', 'Night'), ('PEO', 'People'), ('PER', 'Performing Arts'), ('SPO', 'Sport'), ('STI', 'Still Life'), ('STR', 'Street'), ('TRA', 'Travel')], default='ABS', max_length=3)),
                ('description', models.CharField(max_length=280)),
            ],
        ),
        migrations.CreateModel(
            name='ImageHasTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgID', models.ManyToManyField(to='search.Image')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=36, unique=True)),
                ('password', models.CharField(max_length=36)),
                ('name', models.CharField(max_length=70)),
                ('dailyQuota', models.DecimalField(decimal_places=0, default=4, max_digits=1)),
                ('systemQuota', models.DecimalField(decimal_places=0, default=3, max_digits=1)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='imagehastag',
            name='tagID',
            field=models.ManyToManyField(to='search.Tag'),
        ),
        migrations.AddField(
            model_name='image',
            name='photographer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Member'),
        ),
    ]
