# Generated by Django 2.0.4 on 2018-04-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='num_of_likes',
            field=models.IntegerField(default=0),
        ),
    ]
