# Generated by Django 2.0.2 on 2018-03-23 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagehastag',
            name='imgID',
        ),
        migrations.RemoveField(
            model_name='imagehastag',
            name='tagID',
        ),
        migrations.AddField(
            model_name='image',
            name='tag',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='ImageHasTag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
