# Generated by Django 2.0.2 on 2018-03-26 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20180324_0404'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='uploadDate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
