# Generated by Django 2.0.2 on 2018-04-03 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20180328_0707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='username',
        ),
        migrations.AlterField(
            model_name='image',
            name='photographer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Member'),
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
