# Generated by Django 2.0.2 on 2018-04-03 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_auto_20180403_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageHasTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagName', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='tag',
        ),
        migrations.AddField(
            model_name='imagehastag',
            name='imgID',
            field=models.ManyToManyField(to='search.Image'),
        ),
        migrations.AddField(
            model_name='imagehastag',
            name='tagID',
            field=models.ManyToManyField(to='search.Tag'),
        ),
    ]
