# Generated by Django 2.0.2 on 2018-04-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_auto_20180409_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='numOfDownloads',
            field=models.IntegerField(default=0),
        ),
    ]
