# Generated by Django 2.0.2 on 2018-04-09 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0009_image_numofdownloads'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='img',
            new_name='fileName',
        ),
    ]
