# Generated by Django 2.0.2 on 2018-04-09 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0010_auto_20180409_2227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='fileName',
            new_name='img',
        ),
    ]
