# Generated by Django 2.0.2 on 2018-04-10 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0011_auto_20180409_2236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='numOfDownloads',
            new_name='num_of_downloads',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='uploadDate',
            new_name='upload_date',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='tagName',
            new_name='tag_name',
        ),
    ]
