# Generated by Django 2.0.2 on 2018-04-10 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0012_auto_20180410_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(choices=[('ABS', 'Abstract'), ('AER', 'Aerial'), ('ANI', 'Animals'), ('ARC', 'Architecture'), ('BLA', 'Black and White'), ('FAM', 'Family'), ('FAS', 'Fashion'), ('FIN', 'Fine Art'), ('FOO', 'Food'), ('JOU', 'Journalism'), ('LAN', 'Landscape'), ('MAC', 'Macro'), ('NAT', 'Nature'), ('NIG', 'Night'), ('PEO', 'People'), ('PER', 'Performing Arts'), ('SPO', 'Sport'), ('STI', 'Still Life'), ('STR', 'Street'), ('TRA', 'Travel')], default='ABS', max_length=3, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Category', to_field='cat_name'),
        ),
    ]
